name: Issue Trigger

on:
  issues:
    types: [opened]  # start automatisch bij nieuw issue

jobs:
  issue_job:
    runs-on: ubuntu-latest

    steps:
      - name: Show issue title
        run: echo "Titel: ${{ github.event.issue.title }}"

      - name: Show issue body
        run: echo "Body: ${{ github.event.issue.body }}"
